version: '3.8'

services:
  web:
    container_name: campus-connect-web
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - WATCHPACK_POLLING=true

# command: sh -c "npm install && npm run dev" # Ensure deps are installed if missing
